Repository zextras/carbonio-preview-ce, pull requests merged in 2022-07, with the labels that each got.

#15 fix: PREV-80 - add missing group at user creation
  package/PKGBUILD
Labels: bug

#13 fix: PREV-72 - Thumbnail generation goes in timeout
  .github/PULL_REQUEST_TEMPLATE.md
  .pre-commit-config.yaml
  THIRDPARTIES
  app/core/services/document_manipulation/document_manipulation.py
  app/core/services/pdf_service.py
  package/PKGBUILD
  requirements.txt
Labels: bug, enhancement

#16 chore: PREV - bump version
  app/controller.py
  package/PKGBUILD
Labels: enhancement
